services:
  object-storage:
    container_name: object-storage
    image: minio/minio
    ports:
      - 10000:9000
      - 10001:9001
    command: server --console-address ":9001" http://object-storage/data{1...2}
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ../../object-storage/data1:/data1
      - ../../object-storage/data2:/data2
    # healthcheck:
    # test: ["CMD", "mc", "ready", "local"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    networks:
      - charitan-go

# volumes:
  
