
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      # For demo purposes only. Do not use in production!
      VAULT_DEV_ROOT_TOKEN_ID: "myroot"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: >
      vault server -dev -dev-root-token-id=myroot -dev-listen-address=0.0.0.0:8200
    healthcheck:
      test: ["CMD", "vault", "status", "-address=http://127.0.0.1:8200"]
      interval: 1s
      timeout: 3s
      retries: 60

  vault-setup:
    image: charitan-go/vault-setup
    build: ../../vault-setup/
    container_name: vault-setup
    depends_on:
      vault:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "\
      export VAULT_ADDR=http://vault:8200 && \
      export VAULT_TOKEN=myroot && \
      echo 'Waiting for Vault to be ready...' && \
      until curl -s http://vault:8200/v1/sys/health | grep -q 'sealed\":false'; do \
         sleep 2; \
      done; \
      echo 'Enabling transit secrets engine...' && \
      vault secrets enable transit && \
      echo 'Creating exportable RSA key \"auth-key\"...' && \
      vault write -f transit/keys/auth-key type=rsa-2048 exportable=true && \
      echo 'Vault setup complete.'" 
    restart: "no"
