services:
  email-server:
    container_name: email-server
    image: charitan-go/email-server
    build: ../../email-server
    environment:
      SERVICE_REGISTRY_URI: service-registry:8500
      ADDRESS: email-server
      MESSAGE_BROKER_USER: rabbitmq
      MESSAGE_BROKER_PASSWORD: secret
    depends_on:
      service-registry:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - charitan-go
