services:
  auth-server:
    container_name: auth-server
    image: charitan-go/auth-server
    build: ../../auth-server
    # ports:
    #   - 8090:8090
    environment:
      DB_HOST: auth-db
      DB_NAME: auth
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_PORT: 5432
      SERVICE_REGISTRY_URI: service-registry:8500
      ADDRESS: auth-server
      JWT_EXPIRATION_DURATION: 24h
      MESSAGE_BROKER_USER: rabbitmq
      MESSAGE_BROKER_PASSWORD: secret
    depends_on:
      auth-db:
        condition: service_healthy
      service-registry:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - charitan-go
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8090/health"]
    #   interval: 1s
    #   timeout: 3s
    #   retries: 60
  auth-db:
    image: postgres:alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d auth -U postgres"]
      interval: 1s
      timeout: 3s
      retries: 60
    networks:
      - charitan-go
