services:
  key-server:
    container_name: key-server
    image: charitan-go/key-server
    build: ../../key-server
    environment:
      SERVICE_REGISTRY_URI: service-registry:8500
      ADDRESS: key-server
      MESSAGE_BROKER_USER: rabbitmq
      MESSAGE_BROKER_PASSWORD: secret
    depends_on:
      # key-db:
      #   condition: service_healthy
      service-registry:
        condition: service_healthy
      message-broker:
        condition: service_healthy
    networks:
      - charitan-go
