services:
  redis:
    image: redis:7.4-bookworm
    container_name: redis 
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - 6379:6379
    networks:
      - charitan-go
  redisinsight:
    image: redis/redisinsight
    container_name: redisinsight 
    ports:
      - 5540:5540
    # environment:
      # RI_APP_HOST: redis
    networks:
      - charitan-go
    depends_on:
      redis: 
        condition: service_healthy


